defaults:
  - data: demo-ffhq          # configs/data/demo-ffhq.yaml
  - task: gaussian_blur        # configs/task/inpainting.yaml
  - model: ffhq256ddpm       # configs/model/ffhq256ddpm.yaml
  - sampler: edm_daps        # configs/sampler/edm_daps.yaml
  - _self_  

# Experiment settings
gpu: 0
batch_size: 10
num_runs: 2
save_dir: ./results
name: daps_gaussian_deblur_ffhq_demo

# Task configuration
task_group: pixel  # pixel, sd, or latent

# Evaluation
eval_fn_list: ['psnr', 'ssim', 'lpips']
eval_fid: True
show_eval: True

# Save options
save_samples: True
save_traj: True
save_traj_video: False
save_traj_raw_data: False

# WandB logging
wandb: False
project_name: 'DAPS'

# Random seed
seed: 42